import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Footer from "./ui/Footer";
import { CustomizedFooter } from "./ui/CustomizedFooter";

const roboto = Roboto({ subsets: ["latin"], weight: "400", style: "normal" });

export const metadata: Metadata = {
  title: "Revista App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
      <CustomizedFooter />
    </html>
  );
}
