import type { Metadata } from "next";
import Navbar from "../ui/Navbar";
import { CustomizedFooter } from "../ui/CustomizedFooter";
import Sidebar from "../ui/Sidebar";


export const metadata: Metadata = {
  title: "Revista App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <Sidebar />
      {children}
    </div>
  );
}
